### ISSUE TITLE
libsumo interface issues

### ISSUE THREAD

**Issue by BUCK111111** [blasf1/MintEDGE#1]
Hi author, when I use the environment for RL learning algorithm, I found that if the environment is called repeatedly, the libsumo interface will have an error, but I can't find a solution, I expect your answer!

Traceback (most recent call last):
  File "/home/wyp/code/MintEDGE/mintedge/mobility.py", line 139, in run
    users = self._get_next_step()
  File "/home/wyp/code/MintEDGE/mintedge/mobility.py", line 353, in _get_next_step
    if cars > libsumo.vehicle.getIDCount():
  File "/home/wyp/anaconda3/envs/MintEDGE/lib/python3.8/site-packages/libsumo/libsumo.py", line 4738, in getIDCount
    return _libsumo.vehicle_getIDCount()
libsumo.libsumo.FatalTraCIError: A network was not yet constructed.

**Comment by blasf1** [comment]
Hi! I see the error says that no sumo network has been constructed. Could you please provide more details about the method you are using to create the network? Is it from coordinates or from a sumo network file? If you provide me with more details I can try to reproduce the error, and we can try to solve the issue :)

**Comment by BUCK111111** [comment]
Thank you very much for your prompt answer, I barely solved the bug yesterday, when I called MintEDGE environment for the second time (the RL algorithm needs to interact with the environment several times for training), it seems that a certain class accidentally called MobilityManager's __del__() method, which resulted in the initialization of the libsumo interface being raised to shut down, since I didn't find out why the __del__() method would be called. Since I haven't found out why the __del__() method was called, my solution now is to comment out __del__() and create a new method to close libsumo.
<img width="1320" alt="Snipaste_2024-04-24_15-32-22" src="https://github.com/blasf1/MintEDGE/assets/91197457/c231fb39-1f2e-4d21-a91a-699f9106943d">

**Comment by blasf1** [comment]
Thanks for pointing this out! Since you solved the issues you encountered, I'll put it as a low priority, but I'll have a look at it, fix it, and merge it ASAP. Thanks!
